name: WordPress CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install Composer Dependencies
        run: composer install
      - name: Install PHPCS
        run: composer global require "squizlabs/php_codesniffer=*"
      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress .
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Node.js Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
