name: WordPress CI/CD

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install PHPCS
        run: composer global require "squizlabs/php_codesniffer=*"
      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress .
      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/wordpress-site:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-dockerhub-username/wordpress-site:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/your/staging/directory
            docker-compose pull wordpress-site
            docker-compose up -d
