name: Go CI

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Change to Go directory
        run: cd go

      - name: Install dependencies
        run: |
          cd go
          go mod tidy

      - name: Run lint
        run: |
          cd go
          golangci-lint run ./...

      - name: Run tests
        run: |
          cd go
          go test -v ./...

      - name: Build
        run: |
          cd go
          go build -o myapp

  deploy:
    needs: lint-test-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./go
          file: ./go/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp-go:latest

      - name: Deploy to staging environment
        run: |
          echo "Deploying to staging environment..."
          # Add deployment steps here
