name: Go CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: go mod tidy
      - name: Run Linter
        run: golangci-lint run
      - name: Run Tests
        run: go test ./...
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/go-app:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-dockerhub-username/go-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/your/staging/directory
            docker-compose pull go-app
            docker-compose up -d
>>>>>>> eacba7c (Deployed to staging env)
>>>>>>> 8b94a48 (Newly Update go.yaml)
